/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus;

import java.time.Clock;
import javax.swing.JOptionPane;
import Fungsi.fungsi;
import java.sql.*;
import java.awt.*;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {
    
    public Statement st;
    public ResultSet rs;
    String sql;
    Connection con = koneksi.koneksi.getKoneksi();
    public static String id;
    
//    public static String id2;
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
        sadmin.setBackground(new java.awt.Color(26,177,136));


        
    }
    public void login(JTextField user, JTextField pass,String db,String a,String b,String c,String d){
        try {
                get();
                String usr = user.getText();
                String pas = pass.getText();
                sql = "SELECT * FROM "+ db +" WHERE "+ a +"='"+ usr +"' AND "+ b +"="+ c +"('"+ pas +"')";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Berhasil Masuk");
                    this.dispose();
                    if(d.equals("admin")){
                        halaman_admin ha = new halaman_admin();
                        ha.show();
                    }else if(d.equals("operator")){
                        halaman_operator ho  = new halaman_operator();
                        ho.show();
                    }else if(d.equals("user")){
                        halaman_user hu = new halaman_user();
                        hu.show();
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password SALAH");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
                user_admin.setText("");
                pass_admin.setText("");
                user_admin.requestFocus();
                operator_id.setText("");
                pass_operator.setText("");
                operator_id.requestFocus();
                user_id.setText("");
                pass_user.setText("");
                user_id.requestFocus();
            }
    }
    public void get(){
        id = user_id.getText();
    }
    
    public static  String getid(){
        return id;
    }
//        public static String getid2(){
//        return id2;
//    }
    
    public Boolean kosong_admin(){
        return (user_admin.getText().equals("") || pass_admin.getText().equals(""));
    }
    
     public Boolean kosong_operator(){
        return (operator_id.getText().equals("") || pass_operator.getText().equals(""));
    }
     
    public Boolean kosong_user(){
        return (user_id.getText().equals("") || pass_user.getText().equals(""));
    }
    public void exit(){
        admin.setBackground(new java.awt.Color(28,42,57));
        operator.setBackground(new java.awt.Color(28,42,57));
        user.setBackground(new java.awt.Color(28,42,57));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        operator = new javax.swing.JButton();
        user = new javax.swing.JButton();
        sadmin = new javax.swing.JPanel();
        soperator = new javax.swing.JPanel();
        suser = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_admin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        user_admin = new javax.swing.JTextField();
        separator_admin1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        pass_admin = new javax.swing.JPasswordField();
        separator_admin2 = new javax.swing.JSeparator();
        masuk_admin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panel_operator = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        operator_id = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pass_operator = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        masuk_operator = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panel_user = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        pass_user = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        masuk_user = new javax.swing.JButton();
        daftar_user = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("EngraversGothic BT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/books-stack-of-three_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("EngraversGothic BT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 42, 57));
        jLabel2.setText("PerPus");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(28, 42, 57));
        jLabel10.setText("Raih impianmu dengan membaca buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 410, 540));

        jPanel2.setBackground(new java.awt.Color(28, 42, 57));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masuk atau Daftar");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 29, -1, -1));

        close.setBackground(new java.awt.Color(28, 42, 57));
        close.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("x");
        close.setToolTipText("Tutup");
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 11, 32, 29));

        admin.setBackground(new java.awt.Color(28, 42, 57));
        admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Admin");
        admin.setBorder(null);
        admin.setBorderPainted(false);
        admin.setContentAreaFilled(false);
        admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin.setOpaque(true);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel2.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 150, 46));

        operator.setBackground(new java.awt.Color(28, 42, 57));
        operator.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        operator.setForeground(new java.awt.Color(255, 255, 255));
        operator.setText("Operator");
        operator.setBorder(null);
        operator.setBorderPainted(false);
        operator.setContentAreaFilled(false);
        operator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        operator.setOpaque(true);
        operator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                operatorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                operatorMouseExited(evt);
            }
        });
        operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorActionPerformed(evt);
            }
        });
        jPanel2.add(operator, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 80, 150, 46));

        user.setBackground(new java.awt.Color(28, 42, 57));
        user.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User");
        user.setBorder(null);
        user.setBorderPainted(false);
        user.setContentAreaFilled(false);
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.setFocusTraversalPolicyProvider(true);
        user.setOpaque(true);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 80, 150, 46));

        sadmin.setBackground(new java.awt.Color(28, 42, 57));

        javax.swing.GroupLayout sadminLayout = new javax.swing.GroupLayout(sadmin);
        sadmin.setLayout(sadminLayout);
        sadminLayout.setHorizontalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        sadminLayout.setVerticalGroup(
            sadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(sadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 130, -1, 3));

        soperator.setBackground(new java.awt.Color(28, 42, 57));

        javax.swing.GroupLayout soperatorLayout = new javax.swing.GroupLayout(soperator);
        soperator.setLayout(soperatorLayout);
        soperatorLayout.setHorizontalGroup(
            soperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        soperatorLayout.setVerticalGroup(
            soperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(soperator, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 130, -1, 3));

        suser.setBackground(new java.awt.Color(28, 42, 57));

        javax.swing.GroupLayout suserLayout = new javax.swing.GroupLayout(suser);
        suser.setLayout(suserLayout);
        suserLayout.setHorizontalGroup(
            suserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        suserLayout.setVerticalGroup(
            suserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.add(suser, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 130, -1, 3));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 590, 140));

        jPanel3.setBackground(new java.awt.Color(28, 42, 57));
        jPanel3.setLayout(new java.awt.CardLayout());

        panel_admin.setBackground(new java.awt.Color(28, 42, 57));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        user_admin.setBackground(new java.awt.Color(28, 42, 57));
        user_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        user_admin.setForeground(new java.awt.Color(255, 255, 255));
        user_admin.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        pass_admin.setBackground(new java.awt.Color(28, 42, 57));
        pass_admin.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_admin.setForeground(new java.awt.Color(255, 255, 255));
        pass_admin.setBorder(null);
        pass_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_admin.setBackground(new java.awt.Color(26, 177, 136));
        masuk_admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_admin.setForeground(new java.awt.Color(255, 255, 255));
        masuk_admin.setText("Masuk");
        masuk_admin.setBorder(null);
        masuk_admin.setContentAreaFilled(false);
        masuk_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_admin.setOpaque(true);
        masuk_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_adminActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Administrator");

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(separator_admin2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separator_admin1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_adminLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(separator_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(pass_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_admin2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(masuk_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_admin, "card4");

        panel_operator.setBackground(new java.awt.Color(28, 42, 57));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Operator ID");

        operator_id.setBackground(new java.awt.Color(28, 42, 57));
        operator_id.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        operator_id.setForeground(new java.awt.Color(255, 255, 255));
        operator_id.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        pass_operator.setBackground(new java.awt.Color(28, 42, 57));
        pass_operator.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_operator.setForeground(new java.awt.Color(255, 255, 255));
        pass_operator.setBorder(null);
        pass_operator.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        masuk_operator.setBackground(new java.awt.Color(26, 177, 136));
        masuk_operator.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_operator.setForeground(new java.awt.Color(255, 255, 255));
        masuk_operator.setText("Masuk");
        masuk_operator.setBorder(null);
        masuk_operator.setContentAreaFilled(false);
        masuk_operator.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_operator.setOpaque(true);
        masuk_operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_operatorActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Operator");

        javax.swing.GroupLayout panel_operatorLayout = new javax.swing.GroupLayout(panel_operator);
        panel_operator.setLayout(panel_operatorLayout);
        panel_operatorLayout.setHorizontalGroup(
            panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operatorLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_operatorLayout.createSequentialGroup()
                        .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masuk_operator, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_operatorLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(operator_id, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panel_operatorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pass_operator, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_operatorLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(249, 249, 249))))
        );
        panel_operatorLayout.setVerticalGroup(
            panel_operatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_operatorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operator_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(8, 8, 8)
                .addComponent(pass_operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(masuk_operator, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_operator, "card2");

        panel_user.setBackground(new java.awt.Color(28, 42, 57));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("User ID");

        user_id.setBackground(new java.awt.Color(28, 42, 57));
        user_id.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        user_id.setForeground(new java.awt.Color(255, 255, 255));
        user_id.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");

        pass_user.setBackground(new java.awt.Color(28, 42, 57));
        pass_user.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        pass_user.setForeground(new java.awt.Color(255, 255, 255));
        pass_user.setBorder(null);
        pass_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bukan anggota?");

        masuk_user.setBackground(new java.awt.Color(26, 177, 136));
        masuk_user.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        masuk_user.setForeground(new java.awt.Color(255, 255, 255));
        masuk_user.setText("Masuk");
        masuk_user.setBorder(null);
        masuk_user.setContentAreaFilled(false);
        masuk_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masuk_user.setOpaque(true);
        masuk_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masuk_userActionPerformed(evt);
            }
        });

        daftar_user.setBackground(new java.awt.Color(28, 42, 57));
        daftar_user.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        daftar_user.setForeground(new java.awt.Color(255, 255, 255));
        daftar_user.setText("Daftar");
        daftar_user.setToolTipText("Daftar gratis");
        daftar_user.setBorderPainted(false);
        daftar_user.setContentAreaFilled(false);
        daftar_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_userActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("User");

        javax.swing.GroupLayout panel_userLayout = new javax.swing.GroupLayout(panel_user);
        panel_user.setLayout(panel_userLayout);
        panel_userLayout.setHorizontalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_userLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_userLayout.createSequentialGroup()
                            .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_userLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(panel_userLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(pass_user, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(63, 63, 63))
                        .addGroup(panel_userLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(daftar_user)
                            .addGap(45, 45, 45)))
                    .addGroup(panel_userLayout.createSequentialGroup()
                        .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_userLayout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel15))
                            .addComponent(masuk_user, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_userLayout.setVerticalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_userLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(pass_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(daftar_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(masuk_user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.add(panel_user, "card2");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 590, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        fungsi.close();
    }//GEN-LAST:event_closeActionPerformed

    private void masuk_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_adminActionPerformed
        // TODO add your handling code here:
       if(kosong_admin()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Peringatan", JOptionPane.ERROR_MESSAGE);
       }else{
            login(user_admin,pass_admin,"tb_admin","username","password","HEX","admin");
       }
    }//GEN-LAST:event_masuk_adminActionPerformed

    private void masuk_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_userActionPerformed
        // TODO add your handling code here:
        if(kosong_user()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            login(user_id,pass_user,"tb_anggota","id_anggota","password","","user");
        }
    }//GEN-LAST:event_masuk_userActionPerformed

    private void masuk_operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masuk_operatorActionPerformed
        // TODO add your handling code here:
        if(kosong_operator()){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data !","Kesalahan", JOptionPane.ERROR_MESSAGE);
        }else{
            login(operator_id,pass_operator,"tb_petugas","id_operator","password","","operator");
        }
    }//GEN-LAST:event_masuk_operatorActionPerformed

    private void operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorActionPerformed
        // TODO add your handling code here:
        panel_admin.setVisible(false);
        panel_user.setVisible(false);
        panel_operator.setVisible(true);
        sadmin.setBackground(new java.awt.Color(28,42,57));
        soperator.setBackground(new java.awt.Color(26,177,136));
        suser.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_operatorActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        
        panel_operator.setVisible(false);
        panel_user.setVisible(false);
        panel_admin.setVisible(true);
        sadmin.setBackground(new java.awt.Color(26,177,136));
        soperator.setBackground(new java.awt.Color(28,42,57));
        suser.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_adminActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        panel_admin.setVisible(false);
        panel_operator.setVisible(false);
        panel_user.setVisible(true);
        sadmin.setBackground(new java.awt.Color(28,42,57));
        soperator.setBackground(new java.awt.Color(28,42,57));
        suser.setBackground(new java.awt.Color(26,177,136));
    }//GEN-LAST:event_userActionPerformed

    private void daftar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_userActionPerformed
        // TODO add your handling code here:
        daftar_user da = new daftar_user();
        da.show();
        this.dispose();
    }//GEN-LAST:event_daftar_userActionPerformed

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_adminMouseExited

    private void operatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_operatorMouseExited

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_userMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
        admin.setBackground(new java.awt.Color(197, 211, 226));
//        operator.setBackground(new java.awt.Color(28,42,57));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_adminMouseEntered

    private void operatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorMouseEntered
        // TODO add your handling code here:
//        admin.setBackground(new java.awt.Color(28,42,57));
        operator.setBackground(new java.awt.Color(197, 211, 226));
//        user.setBackground(new java.awt.Color(28,42,57));
    }//GEN-LAST:event_operatorMouseEntered

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
        user.setBackground(new java.awt.Color(197, 211, 226));

    }//GEN-LAST:event_userMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JButton close;
    private javax.swing.JButton daftar_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton masuk_admin;
    private javax.swing.JButton masuk_operator;
    private javax.swing.JButton masuk_user;
    private javax.swing.JButton operator;
    private javax.swing.JTextField operator_id;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_operator;
    private javax.swing.JPanel panel_user;
    private javax.swing.JPasswordField pass_admin;
    private javax.swing.JPasswordField pass_operator;
    private javax.swing.JPasswordField pass_user;
    private javax.swing.JPanel sadmin;
    private javax.swing.JSeparator separator_admin1;
    private javax.swing.JSeparator separator_admin2;
    private javax.swing.JPanel soperator;
    private javax.swing.JPanel suser;
    private javax.swing.JButton user;
    private javax.swing.JTextField user_admin;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
